destination: ./docs
collections_dir: collections
collections:
  mainpages:
    output: true
    permalink: /:name
    order:
      - hello.html
      - questionqueue.md
      - library.md
      - archive.html
  posttags:
    output: true
    permalink: /tags/:name
  vocabcontent:
  thankyoucontent:
  questionqueuecontent:
    order:
      - decaffeination.md
      - lift.md
      - dutch-orange.md
      - champagne-bubbles.md
      - helium.md
      - airport-funding.md
      - beer-glasses.md
      - mountain-measurements.md
      - blank-9.md
      - banana.md
      - blank-11.md
      - wind-chill.md
      - freezer-burn.md
      - moths.md
      - malt.md
      - tree-rings.md
      - holiday-date-determinations.md
      - macaroni-holes.md
      - water-towers.md
      - zip-codes.md
      - straws-and-hot-liquids.md
      - bowling-alleys.md
      - uv-light-and-nail-polish.md
      - bug-breath.md
      - staleness.md
      - spicy-snot.md
      - eye-black.md
      - baby-animal-names.md
      - twenty-twenty-vision.md
      - tone-deaf.md
      - camera-focus.md
      - salamander-tadpoles.md
      - night-vision.md
      - fluorescence.md
      - water-taste.md
      - dry-cleaning.md
      - unsalty-salt.md
      - international-power-plugs.md
      - natural-flavors.md
      - grey-eyelashes.md
      - pineapple-economics.md
      - wheel-drive.md
      - mosquitoes-and-blood.md
      - sunscreen-half-life.md
      - license-plates.md
      - hyphenation.md
      - ungolden-gold.md
      - silica-gel-packets.md
      - vitamin-letters.md
      - cloud-types.md
      - three-d-glasses.md
      - rear-view-mirror.md
      - positively-charged-lightning.md
      - photochromic-lenses.md
      - melody-harmony.md
      - exonyms-endonyms.md
      - italic-light-grids.md
      - warped-air.md
      - euler-number.md
      - nation-state-hierarchies.md
      - candle-smoke.md
      - self-pollination.md
      - coconut-dots.md
      - pockets-sewn-shut.md
      - street-names.md
      - orange.md
      - bicycle-efficiency.md
      - broken-legged-horses.md
      - wine-tasting-jargon.md
      - water-tension.md
      - animal-eyes.md
      - sonic-boom.md
      - tautonyms.md
      - alphabet-taxonomy.md
      - shorthand-stenography.md
      - snowflake-similarity.md
      - royal-titles.md
      - moon-cactus.md
      - pumpkin-air.md
      - yellow-vision-and-cones.md
      - wheels-on-film.md
      - yeast.md
      - copyless-carbon-paper.md
      - sohcahtoa.md
      - moon-dark-side.md
      - city-name-origins.md
      - fizzy-water.md
      - asparagus-growth.md
      - static.md
      - reptile-hibernation.md
      - do-re-mi.md
      - boxed-chocolates.md
      - penmanship-dialects.md
      - mule-hinny.md
      - color-spectrum-wheel.md
      - sun-moon-size.md
      - sunset-rise-times.md
      - cuts-of-gems.md
      - stainless-steel-scent-removal.md
      - fruit-vegetable.md
  librarycontent:
    order:
      - golden-press.md
      - bbc-earth.md
      - calvin-and-hobbes.md
      - trader-joes.md
      - freakonomics.md
      - p5.md
      - charley-harper.md
      - ted-ed.md
      - radiolab.md
      - flatland.md
      - wow-in-the-world.md
      - pentel-rolling-writers.md
      - random-house-thesaurus.md
      - 642-tiny-things-to-draw.md
      - coursera-information-visualization-specialization.md
      - sketchbook-skool.md
      - sunday-sketching.md
      - yoobi-highlighters.md
      - painting-nature-in-watercolor.md
      - this-is-rembrandt.md
      - kirby.md
      - html-css-js-jquery.md
      - learning-responsive-web-design.md
      - tufte-books.md
permalink: /:slug
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/tags"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"
paginate: 7
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
