destination: ./docs
collections_dir: collections
collections:
  mainpages:
    output: true
    permalink: /:name
  posttags:
    output: true
    permalink: /tags/:name
  vocabcontent:
  thankyoucontent:
  questionqueuecontent:
  librarycontent:
permalink: /:slug
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/tags"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"
paginate: 7
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
